modLoader="javafml"

loaderVersion="[36,)"

license="Public Domain"

issueTrackerURL="https://github.com/OroArmor/SlimeBlockInRedstoneTab/issues"

[[mods]]
itemIcon="minecraft:slime_block"

configBackground="minecraft:slime_block"

modId="slimeblockredstone"

version="2.1.1"

displayName="Slime Block In Redstone Tab"

displayURL="https://www.curseforge.com/minecraft/mc-mods/slime-block-in-the-redstone-tab"

logoFile="icon.png"

credits="Thanks to OroArmor for making the Fabric versions"

authors=["RedRoseWarrior1 aka DevMaster1015 for the forge versions","OroArmor for the Fabric versions"]

description='''
This mod allows you to move around items in the creative inventory to different and newly created tabs'''

# Base Forge
[[dependencies.slimeblockredstone]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

# Base Minecraft
[[dependencies.slimeblockredstone]]
    modId="minecraft"
    mandatory=true
versionRange="[1.16.5,1.17]"
    ordering="NONE"
    side="BOTH"
